#%RAML 1.0 DataType
type: object
properties:
  lastname:
    type: string
    description: The field contains header items
  name:
    type: string
    description: The field contains the user details
  timmeZone:
    type: string
    description: The field contains the user details
  offfSet:
    type: string
    description: The field contains the user details
  fullName:
    type: string
    description: The field contains the user details
  temperatureCelcius:
    type: number
    description: The field contains the user details
  dateTime:
    type: string
    description: The field contains the user details
  city:
    type: string
    description: The field contains the user details
  location:
    type: string
    description: The field contains the user details